[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "solsysgen"
version = "0.1.0"
description = "Tiny solar system generator example"
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "samanbehjou"}]
dependencies = ["numpy"]

[tool.setuptools]
packages = ["solsysgen", "solsysgen.utils"]

